### ISSUE TITLE
Create a new admin superuser

### ISSUE THREAD

**Issue by semakamalapane** [toniamichael94/MainProjectCOS301#104]
Create a new admin person who can also assign roles in case something happens to the super user

**Comment by Isabel01** [comment]
The new admin role has been created now only thing is that if it assigns a super user it needs to unassign the existing super user to a normal user and assign a new super user and

**Comment by Isabel01** [comment]
Lol .. sorry I created the issue didn't see this one

**Comment by Isabel01** [comment]
This is now complete default admin user gets created with super user, super user can now also assign new admin user and and admin user can assign new super user
