### ISSUE TITLE
Super user and Admin should not be able to change their role 

### ISSUE THREAD

**Issue by Isabel01** [toniamichael94/MainProjectCOS301#127]
Super user and admin user should not be able to change their own roles unless it is to reassign themselves then they will become a normal user ....

**Comment by semakamalapane** [comment]
Superuser must not be able to change their role to cafeteria manager or any other roles or else there will be no superuser anymore

**Comment by Isabel01** [comment]
This has been done by only giving certain names in a drop-down to choose from which will not include the super user or the admin user names thus they can not change their own names
