### ISSUE TITLE
Invoice states that it is paid

### ISSUE THREAD

**Issue by Isabel01** [toniamichael94/MainProjectCOS301#168]
The invoice states that it is paid ... we should really look into this to rather display no status

![invoice](https://cloud.githubusercontent.com/assets/10923738/10665160/6cbb2372-78c9-11e5-8d75-0cbaba53a3e5.PNG)

**Comment by Isabel01** [comment]
I have tried to take it out but did not suceed

**Comment by RendaniDau** [comment]
removed the status
