### ISSUE TITLE
Browsers saving limit as username

### ISSUE THREAD

**Issue by Lana01** [toniamichael94/MainProjectCOS301#26]
Browsers are saving the limit as the username when signing up.

**Comment by Isabel01** [comment]
I don't see this problem anymore - we need to investigate if it still exist ;-)

**Comment by Isabel01** [comment]
hehehehe sorry did not want to close the issue ... my bad....

**Comment by Isabel01** [comment]
This issue has been fixed, the layout of the sign up page had to be altered so that the username will be filled in right above the password field That solved the issue. :-)  :+1:
