### ISSUE TITLE
Dropdown for employee Id on finance page

### ISSUE THREAD

**Issue by toniamichael94** [toniamichael94/MainProjectCOS301#41]

**Comment by semakamalapane** [comment]
I'm trying to get the bill to show but it just won't

**Comment by semakamalapane** [comment]
It shows everything as successful (even the things that shouldn't be) and it displays [object Object] instead of the actual bill. If anyone can figure it out please do

**Comment by semakamalapane** [comment]
Rendani got this working with jsreport
