### ISSUE TITLE
Out of stock notifications 

### ISSUE THREAD

**Issue by toniamichael94** [toniamichael94/MainProjectCOS301#88]
Let user know if the ingredients to the item they ordered are in stock

**Comment by Isabel01** [comment]
This is almost done it has just a small bug I will fix as soon as I can ;-)

**Comment by Isabel01** [comment]
This issue is linked with issue #71

**Comment by semakamalapane** [comment]
please check cause when the item has an empty ingredient it doesn't have a checkbox (can't be added to plate) and when inventory items are updated from the browser it doesn't work properly

**Comment by Isabel01** [comment]
The reason for this is that the database will return that the empty ingredient can't be found in the database and thus it does not have stock of this thus not must not be allowed for a menu item to have an empty ingredient when creating the menu item the empty ingredient should not be stored in the ingredient list then this issue will not happen, I am going to assign an issue to fix this problem to Elana whom created the add ingredients to menu item
